### PR TITLE
Add Travis CI configuration

### PR DESCRIPTION
**Pull request by paultcochrane**
This adds a configuration file for the Travis Continuous Integration build and test service (http://travis-ci.org).  It is possible with Travis-CI to build a module and run its tests for various Perl versions; it is free to use for open source projects and can be easily connected to one's GitHub account such that pushing to a repo automatically triggers a build on Travis-CI.

Adding this confirguration file and testing it on Travis showed that the tests for `Heap::Simple::XS` fail on Perl versions 5.18 and 5.20, which is good to know and something which needs to be investigated, possibly in another GitHub issue.

### CODE REVIEW

**Comment by hoehrmann** [comment]
I am not really a fan of the duplication of content (like stating the dependencies in Makefile.PL and the actual module code and then also again here); I gather there is a distzilla module that might be able to create some or all of the file automatically, but didn't see anything for MakeMaker. It would seem better if "Travis CI" added support for the normal Perl conventions here, but I guess for them there is some benefit in a more data-driven "generic" approach... I'll probably try to check out Travis CI first before deciding what to do with this PR.

**Comment by paultcochrane** [comment]
Maybe there's a better way to do this; unfortunately I don't know how to get MakeMaker to automatically install the dependencies before running the test suite.  You're right, DistZilla does this (`dzil authordeps | cpanm`), however I don't know if it's really necessary to convert S::IS::P to DistZilla.  Interestingly enough, Travis knows enough about Perl to run `perl Makefile.PL; make test` automatically, hence why this doesn't appear in the config.  BTW: the Perl docs are here: http://docs.travis-ci.com/user/languages/perl/.

**Comment by paultcochrane** [comment]
Update: I just checked to see if the `install:` section is needed and it turns it out it's not :-)  If you wish, I can rebase this branch to improve the history and resubmit the PR.

**Comment by paultcochrane** [comment]
Replaced by PR #16.

**Pull request closed without merging**
